import { Component, input, model, ModelSignal } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';

@Component({
  selector: 'app-automatic-gen-sub-form',
  standalone : true,
  imports: [FormsModule],
  templateUrl: './automatic-gen-sub-form.component.html',
  styleUrl: './automatic-gen-sub-form.component.scss'
})
export class AutomaticGenSubFormComponent  {

    //[(ngModel)]="deviseTempRef()!.code" , ....
        objectTempRef :ModelSignal<any> = model(null);

        idKeyName = input("id"); //or "code" or "ref" or "num" or ...
        withAutoGeneratedId = input(false); // or true 
        
        modeRef = model("newOne"); //or "existingOne"

        objectKeysArray(obj:object):any[]{
          return Reflect.ownKeys(obj);
        }
    
        isNoEditableId(attrName:string){
          if(this.idKeyName() != attrName) return false;
          /* else is key attr*/
          if(this.withAutoGeneratedId())return true;
          if(this.modeRef()!="newOne") return true;
          return false;
         }

}
