import { Component, input, InputSignal, model, ModelSignal } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { ObjectHelper } from '../../../helper/object-helper';

@Component({
  selector: 'app-automatic-gen-sub-form',
  standalone : true,
  imports: [FormsModule],
  templateUrl: './automatic-gen-sub-form.component.html',
  styleUrl: './automatic-gen-sub-form.component.scss'
})
export class AutomaticGenSubFormComponent  {

    //[(ngModel)]="deviseTempRef()!.code" , ....
        objectTempRef :ModelSignal<any> = model(null);

        objectHelperRef =input<ObjectHelper<any,any> | null>(null);

        modeRef = model("newOne"); //or "existingOne"

        objectKeysArray(obj:object):any[]{
          return Reflect.ownKeys(obj);
        }
    
        isNoEditableId(attrName:string){
          if(this.objectHelperRef()!.classHelper.idKeyName != attrName) return false;
          /* else is key attr*/
          if(this.objectHelperRef()!.classHelper.withAutoGeneratedId)return true;
          if(this.modeRef()!="newOne") return true;
          return false;
         }

}
