//meta-data liée à une classe (sans éléments spécifique à une instance)

import { FieldHelper } from "./field-helper";

export class ClassHelper{
    constructor(
        public entityName :string ="Entity", //alias "className"
        public withAutoGeneratedId :boolean =true, 
        public idKeyName :string ="id",
        public essentialFieldNames: string[]=[] ,
        public fieldHelperMap : Map<string,FieldHelper> = new Map<string,FieldHelper>()
    ){}
}