import { FieldHelper } from "./field-helper";

export interface ObjectHelper<T,I>{
    getEntityTypeName():string ; //ex: return "Devise" or ...
    buildEmptyObject() :T; //to code as return new T();
    getId(obj:T):I; //return id/pk of obj
    withAutoGeneratedId() : boolean;
    essentialFieldNames() : string[]; //to display in table row or ...
    getIdKeyName() : string;
    getFieldHelper(fieldName:string):FieldHelper|null;
}