import { FieldHelper } from "../../shared/helper/field-helper";
import { ObjectHelper } from "../../shared/helper/object-helper";
import { Qcm } from "../data/qcm";

export class QcmHelper implements ObjectHelper<Qcm,String> {
        withAutoGeneratedId(): boolean { return false;  }
        getId(obj: Qcm): string { return obj.id??"?"; };
        getIdKeyName(): string {return "id"; }
        buildEmptyObject(): Qcm { return new Qcm(); };
        getEntityTypeName(): string { return "Qcm";  };
        essentialFieldNames(): string[] {return ["id","title"]; }
        getFieldHelper(fieldName:string):FieldHelper|null{
                switch(fieldName){
                        case "id" : return new FieldHelper("id");
                        case "title" : return new FieldHelper("title");
                        //case "change" : return new FieldHelper("change","number",1);
                        default : return null;//NB:FieldHelper(fieldName,fieldType,defaultValue)
                }
        }
}