import { FieldHelper } from "d2f-ngx-util";
import { AbstractObjectHelper } from "d2f-ngx-util";
import { Qcm } from "../data/qcm";

export class QcmHelper extends AbstractObjectHelper<Qcm,String> {
        constructor(){
                super("Qcm",true,"id"); //EntityName,withAutoGeneratedId,idKeyName
        }
        getId(obj: Qcm): string { return obj.id??"?"; };
        buildEmptyObject(): Qcm { return new Qcm(); };
        initObjectHelper(){
               this.classHelper.essentialFieldNames = ["id","title"]
               this.classHelper.fieldHelperMap.set("id",new FieldHelper("id"))
               this.classHelper.fieldHelperMap.set("title",new FieldHelper("title"))
               //NB:FieldHelper(fieldName,fieldType,defaultValue)
        }
}


